version: '3.8'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"

  localstack:
    image: localstack/localstack:1.4
    environment:
      SERVICES: s3,ssm,iam,cloudformation
      AWS_DEFAULT_REGION: us-east-1
    ports:
      - "4566:4566"

  app:
    build: ../..
    env_file:
      - ../../.env
    environment:
      DB_URL: jdbc:mysql://mysql:3306/test
      DB_USERNAME: root
      DB_PASSWORD: example
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: us-east-1
    depends_on:
      - mysql
      - localstack
    ports:
      - "8080:8080"
