name: Deploy to Kubernetes
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.27.1'
      - name: Configure kubeconfig
        run: echo "${{ secrets.KUBECONFIG }}" > kubeconfig && chmod 600 kubeconfig
      - name: Deploy
        env:
          KUBECONFIG: kubeconfig
        run: |
          cd deploy/kubernetes
          ./deploy.sh


