name: Manage Infrastructure
on:
  workflow_dispatch:

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy CloudFormation
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          HOSTED_ZONE: ${{ secrets.HOSTED_ZONE }}
        run: |
          cd deploy/cloudformation
          ./deploy.sh "$DB_PASSWORD" "${HOSTED_ZONE:-example.com.}"
